### ISSUE TITLE
Standing on bars issue

### ISSUE THREAD

**Issue by Fr0dech** [LambdaGaming/ricochet-source-2#25]
Ricochet bars under pyramid jumpers on rc_deathmatch don't push players off. (Other maps also worth checking, didn't test every one out, it will be easier in hammer anyway.

**Comment by LambdaGaming** [comment]
Looking at the original game, those bars shouldn't even be accessible, but I'm not sure how. From what I can tell, the original map doesn't have any triggers or clips that the player could hit before reaching those bars. For now, I'll add trigger_push entities back to those bars until I can figure out what the original map is using.

**Comment by LambdaGaming** [comment]
The issue is fixed but I can't figure out how to upload the map. I guess I haven't updated any of them since they changed how maps are handled on asset.party. The issue will stay open until I can figure out how to do that lol.
